# Generated by Django 4.1.7 on 2023-06-09 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nohp', models.CharField(default='', max_length=15)),
                ('no_order', models.CharField(default='', max_length=100)),
                ('ao', models.CharField(default='', max_length=50)),
                ('witel', models.CharField(default='', max_length=50)),
                ('ncli', models.CharField(default='', max_length=50)),
                ('wfm_id', models.CharField(default='', max_length=50)),
                ('layanan', models.CharField(default='', max_length=50)),
                ('flag_deposit', models.CharField(default='', max_length=50)),
                ('paket', models.CharField(default='', max_length=50)),
                ('product', models.CharField(default='', max_length=50)),
                ('cat_provider', models.CharField(default='', max_length=50)),
                ('cust_addr', models.CharField(default='', max_length=50)),
                ('cust_addr_new', models.CharField(default='', max_length=50)),
                ('k_contact', models.CharField(default='', max_length=50)),
                ('od', models.CharField(default='', max_length=50)),
                ('durasi', models.CharField(default='', max_length=50)),
                ('tahapan_instalasi', models.CharField(default='', max_length=50)),
                ('task', models.CharField(default='', max_length=50)),
                ('act_start', models.DateField(default=django.utils.timezone.now)),
                ('schedule_labor', models.CharField(default='', max_length=50)),
                ('lok_odp_pelanggan', models.CharField(default='', max_length=50)),
                ('lat', models.CharField(default='', max_length=50)),
                ('lon', models.CharField(default='', max_length=50)),
                ('amcrew', models.CharField(default='', max_length=120)),
                ('teknisi', models.CharField(default='', max_length=50)),
                ('tgl_install', models.DateField(null=True)),
                ('status', models.CharField(default='', max_length=50)),
                ('tgl_status', models.DateField(null=True)),
                ('durasi_jam', models.CharField(default='', max_length=50)),
                ('status_message', models.CharField(default='', max_length=50)),
                ('inet_onu', models.CharField(default='', max_length=50)),
                ('rx_level', models.CharField(default='', max_length=50)),
                ('usg_inet', models.CharField(default='', max_length=50)),
                ('usg_iptv', models.CharField(default='', max_length=50)),
                ('status_voice', models.CharField(default='', max_length=50)),
                ('clid', models.CharField(default='', max_length=50)),
                ('last_sess_inet', models.CharField(default='', max_length=50)),
                ('tgl_ukur', models.DateField(null=True)),
                ('appointment', models.CharField(default='', max_length=50)),
                ('error_code', models.CharField(default='', max_length=50)),
                ('engineer_mode', models.CharField(default='', max_length=50)),
                ('kendala', models.CharField(default='', max_length=50)),
                ('sub_kendala', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
