# Generated by Django 4.1.7 on 2023-06-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'managed': False},
        ),
    ]
