# Generated by Django 4.1.7 on 2023-06-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_myuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='kolom_data_hsi',
        ),
    ]
